# This file generates the GitHub Actions matrix
---
include:

 # sweep
  - board: seeeduino_xiao_ble
    shield: sweep_dongle dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: sweep_dongle

#  - board: nice_nano_v2
#    shield: sweep_left led_indicator
#    snippet: studio-rpc-usb-uart
#    artifact-name: sweep_central_left

  - board: nice_nano_v2
    shield: sweep_left led_indicator
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sweep_peripheral_left

  - board: nice_nano_v2
    shield: sweep_right led_indicator
    artifact-name: sweep_peripheral_right

 # totem
#  - board: seeeduino_xiao_ble
#    shield: totem_dongle rgbled_adapter
#    snippet: studio-rpc-usb-uart
#    artifact-name: totem_dongle

  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: totem_central_left

#  - board: seeeduino_xiao_ble
#    shield: totem_left rgbled_adapter
#    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
#    artifact-name: totem_peripheral_left

  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_adapter
    artifact-name: totem_peripheral_right

  # reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
