draw_config:
  append_colon_to_layer_header: false
  draw_key_sides: true

  svg_extra_style: |
    svg.keymap {
      font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
      font-size: 10px;
      font-weight: bold;
    }
 
    text.label {
      stroke: #dfdfde;
      stroke-width: 12;
      stroke-linejoin: round;
    }

    rect.combo, rect.combo-separate {
      opacity: 1.00;
      stroke: #c9cccf;
      stroke-width: 0.5;
      fill: #d7eaed;
    }
    path.combo {
      stroke-dasharray: 0, 0;
      stroke-opacity: 1.00;
    }

    rect.held, rect.combo.held {
      fill: #ebdada;
    }

    .trans.tap, .ghost.tap {
      opacity: 0.5;
    }

    .shifted {
      translate: -9px 3px;
      opacity: 0.3;
    }

    .toggle.shifted {
      translate: -12px 17px;
      opacity: 1.0;
    }
    .toggle.hold {
      translate: 12px -25px;
    }

    .text_with_symbol.tap {
      translate: -1px 1px;
    }
    .text_with_symbol.shifted {
      translate: 8px 13px;
      font-size: 8px;
      opacity: 1.0;
    } 

    .combo.text_with_symbol.tap {
      translate: -1px 1px;
    }
    .combo.text_with_symbol.shifted {
      translate: 7px 5px;
      font-size: 8px;
      opacity: 1.0;
    }
  
  glyph_tap_size: 14
  glyph_hold_size: 8
  glyph_shifted_size: 8
  

parse_config:
  zmk_remove_keycode_prefix: ["DE_"]
    
  sticky_label: $$mdi:circle-small$$
  toggle_label: $$mdi:toggle-switch$$
  trans_legend:
    tap: $$mdi:chevron-down$$
    type: trans


  raw_binding_map: 
    '&sys_reset': $$mdi:backup-restore$$
    '&bootloader': $$mdi:progress-download$$
    '&caps_word': Caps Word
    '&alt_tabber': $$mdi:swap-horizontal$$
   
    '&out OUT_BLE': $$mdi:bluetooth$$
    '&out OUT_USB': $$mdi:usb$$
    '&out OUT_TOG':
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
      shifted: $$mdi:usb$$
      type: toggle
    
    '&bt BT_CLR': BT CLR
    '&bts_0':
      tap: $$mdi:bluetooth-connect$$
      shifted: '0'
      type: text_with_symbol
    '&bts_1':
      tap: $$mdi:bluetooth-connect$$
      shifted: '1'
      type: text_with_symbol
    '&bts_2':
      tap: $$mdi:bluetooth-connect$$
      shifted: '2'
      type: text_with_symbol
    '&bts_3':
      tap: $$mdi:bluetooth-connect$$
      shifted: '3'
      type: text_with_symbol
    '&bts_4':
      tap: $$mdi:bluetooth-connect$$
      shifted: '4'
      type: text_with_symbol
    
    '&mkp LCLK': $$mdi:cursor-default-click-outline$$
    '&mkp RCLK': $$mdi:cursor-default-click$$
    '&mkp MB3':
      tap: $$mdi:cursor-default-click-outline$$
      shifted: 3
      type: text_with_symbol
    '&mkp MB4':
      tap: $$mdi:cursor-default-click-outline$$
      shifted: 4
      type: text_with_symbol
    '&mkp MB5':
      tap: $$mdi:cursor-default-click-outline$$
      shifted: 5
      type: text_with_symbol

    '&mmv MOVE_UP':
      tap: $$mdi:mouse-outline$$
      shifted: $$mdi:arrow-up$$
      type: text_with_symbol
    '&mmv MOVE_DOWN':
      tap: $$mdi:mouse-outline$$
      shifted: $$mdi:arrow-down$$
      type: text_with_symbol
    '&mmv MOVE_LEFT':
      tap: $$mdi:mouse-outline$$
      shifted: $$mdi:arrow-left$$
      type: text_with_symbol
    '&mmv MOVE_RIGHT':
      tap: $$mdi:mouse-outline$$
      shifted: $$mdi:arrow-right$$
      type: text_with_symbol

    '&msc SCRL_UP':
      tap: $$mdi:mouse-scroll-wheel$$
      shifted: $$mdi:arrow-up-thin$$
      type: text_with_symbol
    '&msc SCRL_DOWN':
      tap: $$mdi:mouse-scroll-wheel$$
      shifted: $$mdi:arrow-down-thin$$
      type: text_with_symbol
    '&msc SCRL_LEFT':
      tap: $$mdi:mouse-scroll-wheel$$
      shifted: $$mdi:arrow-left-thin$$
      type: text_with_symbol
    '&msc SCRL_RIGHT':
      tap: $$mdi:mouse-scroll-wheel$$
      shifted: $$mdi:arrow-right-thin$$
      type: text_with_symbol
      
    '&kp LC(TAB)': Tab Right
    '&kp LC(LS(TAB))': Tab Left
    '&kp LA(TAB)': TaskSW →
    '&kp LA(LS(TAB))': TaskSW ←
    '&kp LA(F4)': Win Close
    '&kp LC(F4)': Tab Close
    '&kp LG(L)': Lock
    '&sleep': Sleep
    '&soft_off': BAT Save
    '&hwp_won': ㅎ₩
    '&hwp_tmp': ㅎ℃
    '&hwp_pm': ㅎ±
    '&hwp_phi': ㅎØ
    '&hwp_kg': ㅎkg
    '&hwp_grm': ㅎg
    '&hwp_mg': ㅎmg
    '&hwp_vac': ㅎVAC
    '&hwp_mm': ㅎmm
    '&uni_mdot': Mid-dot
    '&sel_ln': Sel-Line
    '&sel_wrd': Sel-Word
    '&studio_unlock' : Studio Unlock
    '&ind_con': Conn status
    '&ind_bat': Batt level

    
  zmk_combos:
    combo_star:   {align: right}
    combo_ret:    {o: -0.25}
    combo_sleep:  {align: top, o: 0.25}
    combo_soft:   {align: top, o: 0.40}
    combo_lock:   {align: top}
    combo_batt:   {align: top}
    combo_conn:   {align: top}

      
  zmk_keycode_map:

    LC(INS): $$mdi:content-copy$$
    LC(C): $$mdi:content-copy$$
    LS(INS): $$mdi:content-paste$$
    LC(V): $$mdi:content-paste$$
    LS(DEL): $$mdi:content-cut$$
    LC(X): $$mdi:content-cut$$
    LC(Z): $$mdi:undo$$
    LC(Y): $$mdi:redo$$

    LC(A): Sel-All
    LC(F): $$mdi:text-search$$
    LC(W): $$mdi:close-box-outline$$
    LA(F4)': $$mdi:close-box-outline$$
    
    LALT: Alt
    RALT: RAlt
    
    SPACE: $$mdi:keyboard-space$$
    # ESC: $$mdi:keyboard-esc$$

    RETURN: $$mdi:keyboard-return$$
    RET: $$mdi:keyboard-return$$
    
    BACKSPACE: $$mdi:backspace-outline$$
    BSPC: $$mdi:backspace-outline$$
    
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$
    
    LCTRL: Ctrl
    RCTRL: RCtrl
    
    LSHFT:  Shift
    LSHIFT:  Shift
    
    RSHFT: Shift
    RSHIFT: Shift

    LGUI: Gui
    RGUI: Gui
    
    TAB: $$mdi:keyboard-tab$$

    CAPS: Caps Lock
    CAPSLOCK: Caps Lock

    SCROLLLOCK: Scroll Lock
    SLCK: Scroll Lock

    KP_NLCK: $$mdi:numeric-off$$

    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break
    
    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    
    C_MUTE: $$mdi:volume-mute$$
    C_VOL_UP: $$mdi:volume-plus$$
    C_VOL_DN: $$mdi:volume-minus$$
    
    C_BRI_UP: $$phosphor:bold/sun$$
    C_BRI_DN: $$phosphor:bold/sun-dim$$
    
    C_POWER: $$mdi:power$$
    C_SLEEP: $$mdi:power-sleep$$
    C_AL_CALC: $$mdi:calculator$$
    
    UP: $$mdi:arrow-up$$
    DOWN: $$mdi:arrow-down$$
    LEFT: $$mdi:arrow-left$$
    RIGHT: $$mdi:arrow-right$$
    
    PG_UP: Page Up
    PG_DN: Page Down
    
    # default
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    
